---
name: CI
on: push

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          args: --release --target=armv7-unknown-linux-gnueabihf
          command: build
          use-cross: true

      - uses: actions/upload-artifact@v3
        with:
          name: bin
          path: target/**/gegensprech


      - run: find .
